### ISSUE TITLE
Edits to Action 3: Develop a Data Ethics Framework. 

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#101]
4. For each action, provide any edits and additional detail to ensure that they accurately and effectively describe needed activities, responsible entities, metrics for assessing progress, and timelines for completion.
5. For each action, provide information about the implementation resources necessary to ensure success of these Action Steps.    

For Action 3: Develop a Data Ethics Framework. 

At CareSet Systems, we ensure that our organization not only honors CMS data privacy policies, but that the practical impact of the patient data extractions that we do on CMS data are wholly in the interests of the patients in question. 

There are a number of academic privacy researchers who use intellectually dishonest methods to discredit the work done by those of us who release public healthcare datasets. Most notably, the method of matching already public information about patients with anonymized data, and representing that the whole of the new data represents a data breach. This is a kind of “privacy violation melodrama” that you must avoid as you develop your ethical frameworks. 

But we must also recognize that there are now more threats than ever due to privacy concerns, with very specific implications. Many corporations have arisen whose core business plan is to use data against people. There are very real long term threats from nation state level technology attackers. The members of your data ethics framework should have some cybersecurity credentials to ensure that they are aware of the landscape of attacking actors. Otherwise, the ethical exercise is a blue-sky discussion that avoids the hard parts of the issue. 

Black box artificial intelligence methods have profound and unforeseeably complex ethical issues. A data ethics framework must be specifically nimble enough to handle the sudden changes that happen when specific AI methods become mature. 

As you seek to protect privacy, be careful, because it is both unethical to use data in the wrong ways, and it is also unethical to allow data to lie fallow. Inaction does not qualify as a moral good when solutions to problems are missed because they require triangulation that is impossible because of siloed and poorly managed data. 

Most importantly, we have sloppy data on critical issues like gun violence, disease states, automobile accidents and climate change. This sloppiness sometimes comes from politically motivated constraints to good data collection. Sometimes, it is considered more politically convenient to erase data that does not support current political rhetoric. Despite recent drama, both US political parties are guilty of this. It is not possible for a Data Ethics Framework to prevent Congress from crippling data collection or to prevent the Executive Branch from ordering data to be deleted. But unless this data ethics frameworks highlights these top-level actions as unethical and establishing ongoing institutional pressure against these trends, then all of the other data positions taken by this framework will ring hollow. It may not be possible for this framework to fix those problems, but it should at least call them out and label them for that they are: unscientific and unethical. 

These suggestions should be specifically merged into measurements for Action 3. Specifically:

*  Does the data ethics framework establish rules that highlight unscientific and unethical data practices, even if they are legally endorsed by a some branch of the Federal Government?
* Does the data ethics framework acknowledge and balance the need for personal privacy regarding data as well as the need to leverage data to ensure that data and data analysis serves citizens most pressing needs? 
* Is the framework response to rapidly changing AI and ML technology shifts? Does the Data Ethics Framework have specific content to measure if rapidly changing AI methods warrant an update to the underlying ethics framework?

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
