### ISSUE TITLE
Edits to Action 13: Assess Data and Related Infrastructure Maturity

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#102]
4. For each action, provide any edits and additional detail to ensure that they accurately and effectively describe needed activities, responsible entities, metrics for assessing progress, and timelines for completion.
5. For each action, provide information about the implementation resources necessary to ensure success of these Action Steps.    

Edits to Action 13: Assess Data and Related Infrastructure Maturity

## Need to assess all cases where data reporting to Congress or the public is broken or delayed

Action 13 should be expanded to include the development of a new catalogue of all cases where agencies are required to provide summaries to Congress. This should include summaries of cases where data failures prevent Congress (and therefore the public) from understanding a central government process that is tracked in a database system. 

This assessment should perform a root-cause analysis of these cases to report and detail what caused them to fail. This is useful for several reasons: 

* It removes any discussion of “what should a database be doing in any case” which makes it difficult to assess the maturity of underlying systems. If Congress is requiring reports, and those reports are inaccurate and/or untimely, then there is no question that the database and data analysis infrastructure has failed. Given Congressional mandates, the reporting requirements for these systems should have been baked into the design of the entire data infrastructure. If the data system were mature, simple reporting would be perfect and instantaneous. This makes discussion of maturity into an objective discussion rather than a subjective one. 
* Many of the failures of data maturity are not going to be strategic failures, but rather failures of tactical matters. Cataloguing the root cause analysis of these specific failures will serve to demonstrate patterns of common tactical failures. This will provide an agency with tools to develop and training to conduct. 
* This accounting should be specific about the contractors involved in failing systems. The preference for the Federal Government to outsource data expertise is sensible. But it is also clear that contractors tend to implement data systems in a manner which optimizes the likelihood that they will be needed in the future. It is an open secret that data systems are frequently broken because contractors fail to implement best practices as they design systems to lock competitors out. While it is an open secret that this practice among contractors is common, not every Federal Contractor approaches data contracts in this way. We need objective information about which Federal contractors tend to build data systems in broken ways. If we agree that failure to report things to Congress is a broken state, this is an excellent opportunity to create accountability for contractor failure and rewards for contractors who have a history of doing the right thing.

The corresponding new measure should be:

* Has a publicly accessible database of agency data reporting obligations, including obligations to Congress, another part of the Federal Government, or to the public. 
* Does this data reporting database detail the reporting requirement,  and to whom it is owed (i.e. another agency, Congress, the public, etc)

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
