### ISSUE TITLE
Edits to Action 15 and 16

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#103]
Action 15: Identify Data Needs to Answer Key Agency Questions
Action 16: Identify Priority Datasets for Agency Open Data Plans

We support this action item. 
## Need to reconsider FOIA prioritization

The FOIA process is horribly slow. Even FOIA requests that are given priority status take years to complete in many cases. 

Most FOIA requests are not for data at all, but rather for snapshots of information that is sometimes held in databases. 

Action 16 should explicitly consider all FOIA requesters to be “stakeholders” in its identification process. A simple way to figure out what data would be valuable for the public is to study what the public has been asking for. If the public wants to understand what an agency is doing with a specific dataset, it is a good bet that the same dataset has central importance to the actions of the agency. FOIA requests are therefore a good proxy for both internal and external customers of agency datasets.   

The “Five Safes” framework is a good but makes no prioritization efforts.

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
