### ISSUE TITLE
Edits to Actions 5, 7, 8, 9, 10, 11, 12 

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#104]
## Action 5: Develop a Repository of Federal Data Strategy Resources and Tools

Action 5 should be extended to reviewing tools that can help with the backup,  auditing and repair of datasets. These tools should specifically include mechanisms to crowd-source data corrections. 

## Action 7: Pilot an Automated Inventory Tool for Data.gov
This should be deprioritized in favor of inventorying the quality of the data in Action Item 13.

## Action 8: Pilot Standard Data Catalogs for Data.gov
This action should state that the “shared code base” should be open source and developed in the open. 

However, this also should be postponed until a government wide data quality review takes place in Action Item 13.

## Action 9: Improve Data Resources for AI Research and Development
This also should be postponed until a government wide data quality review takes place in Action Item 13.

## Action 10: Improve Financial Management Data Standards
There are multiple IRS related data systems that are poorly designed and continue to hamper public review of data on nonprofits, etc. Before undertaking a review to fix financial data standards, a careful review of data that is currently available in these domains should be conducted, and efforts to fix the problems undertaken. In many cases outside watch-dog agencies are fully capable of providing the data analysis needed to meet the goals of the President’s Management Agenda, but cannot because they have to deal with bad data that arises from poorly implemented data systems. 

## Action 11: Improve Geospatial Data Standards
This should be amended to say “to cause additional damage to the national interest, security, or defense of the nation.”  

The reality is that soldiers and Marines use devices to track their jogs, and that geodata poses a national security risk. Google Street view shows the exact location of electrical facilities and that poses a national security risk. 

If the government wants to withhold datasets that reveal additional security risks, that seems reasonable. But refusing to release new geodata that shows a way to attack national infrastructure that is already simple to find in 10 different ways is nonsensical. 

That means that this item must catalog publicly available geo datasets and understand what national security risks are endemic in the area of street-view cars, privately launched and owned photo satellites, and inexpensive drones. And then only refuse to release geospatial data that encompases additional risks in that context. Otherwise you are considering not releasing dangerous squirtgun technology into a landscape that is clearly already “bazooka-ville”. 

Threats to the national interests, security, or the defense of the nation that would exist to the same degree with or without the release of data assets should not prevent the release of those data assets. 

## Action 12: Constitute a Diverse Data Governance Body
This needs to be fleshed out, but at a minimum: 

This should include researchers who would make use of the data to answer significant questions
This should include members of the public who have been impacted by relevant data breaches
This should include data journalists
This should include data experts and statisticians

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
