### ISSUE TITLE
CareSet/Trotter Strategy Notes on multiple action items

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#105]
This PDF document details areas for action that are not covered at all or well in the action plan

[Good, Bad and Non Data Strategy.pdf](https://github.com/GSA/data-strategy/files/3371126/Good.Bad.and.Non.Data.Strategy.pdf)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
