### ISSUE TITLE
Edits to Action 4: Develop a Data Protection Toolkit

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#106]
Action 4 comments are complex enough that we are submitting them as a PDF.

[CareSet-Trotter Comments on Action 4.pdf](https://github.com/GSA/data-strategy/files/3371133/CareSet-Trotter.Comments.on.Action.4.pdf)

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
