### ISSUE TITLE
Add GovDelivery subscription widget to homepage and news

### ISSUE THREAD

**Issue by ruxftc** [GSA/data-strategy#23]
Please add the GovDelivery subscription widget to the homepage, the news page and the actual blog post.

The code is in the txt file. Thanks!

[govd-subscribe.txt](https://github.com/GSA/data-strategy/files/2372510/govd-subscribe.txt)

**Comment by rebeccawilliams** [comment]
@ruxftc & @philipashlock, does this still need to be added?

**Comment by adborden** [comment]
Closing as stale, feel free to reopen.
