### ISSUE TITLE
compromise vs comprise

### ISSUE THREAD

**Issue by mhart-epa** [GSA/data-strategy#247]
at strategy.data.gov/background, first bullet under mission statement you wrote compromise when you meant _comprise_? The Federal Data Strategy, which **compromises** the Mission Statement, Principles, and Practices, provides a whole-of-government vision and offers guidance on how agencies should manage and use Federal data.

**Comment by mogul** [comment]
We've just landed a fix and it will roll out soon. Thanks for your report!
