### ISSUE TITLE
Small Business Administration - Federal Data Strategy Comments

### ISSUE THREAD

**Issue by nreboja** [GSA/data-strategy#32]
If you haven't already reviewed directions for provide feedback on the Federal Data Strategy, please first read http://strategy.data.gov/feedback/

When you create a new issue here on GitHub please fill out the template below. You can delete these instructions 
[Federal Data Strategy Comments.xlsx](https://github.com/GSA/data-strategy/files/2587033/Federal.Data.Strategy.Comments.xlsx)

-----
Feedback Type (Practices, Use Case, Other)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the draft Practices, the Federal Data Strategy team values your input! You can review the [final Practices](strategy.data.gov/practices) and read more on [how the team revised the Practices based on feedback](https://strategy.data.gov/assets/docs/revising-the-practices-based-on-feedback.pdf) on [Strategy.data.gov](Strategy.data.gov). You can also stay abreast of Federal Data Strategy updates by signing up by following [Strategy.data.gov/News](Strategy.data.gov/News).
