### ISSUE TITLE
FPF Comments on Federal Data Strategy

### ISSUE THREAD

**Issue by SaraNolanCollins** [GSA/data-strategy#37]
[FPF Comments on Federal Data Strategy.pdf](https://github.com/GSA/data-strategy/files/2601991/FPF.Comments.on.Federal.Data.Strategy.pdf)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the draft Practices, the Federal Data Strategy team values your input! You can review the [final Practices](strategy.data.gov/practices) and read more on [how the team revised the Practices based on feedback](https://strategy.data.gov/assets/docs/revising-the-practices-based-on-feedback.pdf) on [Strategy.data.gov](Strategy.data.gov). You can also stay abreast of Federal Data Strategy updates by signing up by following [Strategy.data.gov/News](Strategy.data.gov/News).
