### ISSUE TITLE
CKAN Association - Draft Practices comments

### ISSUE THREAD

**Issue by jqnatividad** [GSA/data-strategy#40]
**Feedback Type (Practices)**

In behalf of the CKAN Association, we welcome and celebrate this initiative as the US Federal Government embrace Data as a Strategic Asset and thank the Federal Data Strategy team for going the extra mile and soliciting feedback.

As the CKAN platform is already used in various levels of government including Data.gov, we are humbled that the CKAN project is already playing a small part in this important initiative, and we look forward to the US Government's input as well as we co-create the platform.

Herewith is the Association's feedback:

* [Google Sheets version](https://docs.google.com/spreadsheets/d/1U_jVb5A6sZKSbTuz2Mmz7uU1bRwlkeey9wLhoC_cfKQ/edit?usp=sharing)
* [Federal Data Strategy draft-practices feedback - CKAN Association.xlsx](https://github.com/GSA/data-strategy/files/2611981/Federal.Data.Strategy.draft-practices.feedback.-.CKAN.Association.xlsx)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the draft Practices, the Federal Data Strategy team values your input! You can review the [final Practices](strategy.data.gov/practices) and read more on [how the team revised the Practices based on feedback](https://strategy.data.gov/assets/docs/revising-the-practices-based-on-feedback.pdf) on [Strategy.data.gov](Strategy.data.gov). You can also stay abreast of Federal Data Strategy updates by signing up by following [Strategy.data.gov/News](Strategy.data.gov/News).
