### ISSUE TITLE
Esri: Comments on Draft Practices

### ISSUE THREAD

**Issue by adamajm** [GSA/data-strategy#41]
Please find attached. Thank you!
[Esri_Fed Data Strategy_Comments_2018-11-23.pdf](https://github.com/GSA/data-strategy/files/2612000/Esri_Fed.Data.Strategy_Comments_2018-11-23.pdf)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the draft Practices, the Federal Data Strategy team values your input! You can review the [final Practices](strategy.data.gov/practices) and read more on [how the team revised the Practices based on feedback](https://strategy.data.gov/assets/docs/revising-the-practices-based-on-feedback.pdf) on [Strategy.data.gov](Strategy.data.gov). You can also stay abreast of Federal Data Strategy updates by signing up by following [Strategy.data.gov/News](Strategy.data.gov/News).
