### ISSUE TITLE
organized then clean out your github issues

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#81]
Hi, 
    This is a meta comment really. 

It is really lovely that you all are accepting comments on things through this github repo. But the fact that it is the websites repo, as well as the place to actually comment on things, is a little confusing. 

Most of the currently open issues relate to the "Federal Data Strategy" comment which is now closed.. time for comments relating to the "2019-2020 Federal Data Strategy Action Plan". 

I suggest you create a new label for both the old and current comment-issues, and then close the old comment-issues. This will make it clear which issues are intended to be reviewed in the current round of examination. 

HTH,
-ft

**Comment by rebeccawilliams** [comment]
Thanks for following along! Closed comments have also been closed as issues. You can review the [final Practices](strategy.data.gov/practices) and read more on [how the team revised the Practices based on feedback](https://strategy.data.gov/assets/docs/revising-the-practices-based-on-feedback.pdf) on [Strategy.data.gov](Strategy.data.gov). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).

**Comment by ftrotter** [comment]
Perfect! Thank you!
