### ISSUE TITLE
What is the deadline? July 5 or July 8th?

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#82]
This page: https://strategy.data.gov/action-plan/
says July 8th. 
This page: https://strategy.data.gov/feedback/
says July 8th
This page: https://www.regulations.gov/document?D=USBC-2019-0001-0001
says July 5th

confusion.

HTH,
-ft

**Comment by rebeccawilliams** [comment]
Hi @ftrotter! 

The comments provided through this site are due July 8th @ midnight ET. This is a short extension past the 30 day Federal Register Notice to allow for additional comments. Comments provided through any channel will be gathered and processed the same way. I hope that helps.
