### ISSUE TITLE
Stae Comments on Federal Data Strategy Year 1 Action Plan

### ISSUE THREAD

**Issue by samwu8912** [GSA/data-strategy#86]
Feedback Type (Question # or Other): 1
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment:  While I thought that many of the action items were logical and indicated a very promising direction, there seemed to be an omission of how new processes or standards would be implemented and enforced. I realize this is Year 1 but, for example, once a Data Ethics Framework with Action 3 is developed by November 2019, what happens to the framework then? Or when the Data Governance Councils from Action 12 move before the Federal Geospatial Data Committee completes the Geospatial Data Standards? The US Census has also already begun to implement new data sharing methods such as the Differential Privacy model. How does that initiative tie into this action plan? One of the hardest parts of data governance is actually making the standards or systems enforceable. I'd love to see more of that process outlined in the action plan. Including pushes for more data sharing before even establishing methods or benchmarks for the quality of datasets with regards to bias, re-identification concerns, timely records, is a dangerous start. 

Feedback Type (Question # of Other): 4
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment: For Action 8, will this relate to the pilot in Action 7? There are different bodies responsible but metadata management loses value if there are multiple metadata systems and models as they are more likely to conflict and burdensome to maintain. Similar to my feedback above, what happens to the pilot after the target completion date of 6 months? Will there be a second iteration or will the pilot just be set aside?

Feedback Type (Question # of Other) 4
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment: For Action 12, I find the completion date for this action add if the OMB council in Action 1 and the data ethics framework from Action 3 are due for completion 2 months later. Is it implied that these bodies will not meet after being constituted until the OMB council and framework are shared out? 

Feedback Type (Question # of Other) 4
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment: Why is Action 2 specifically about data science? How is data science being defined? Does it include data governance models? Or identifying erroneous information and tracing down what process change would be required to fix it? There's a rather large range of system design and detailed work involved with data and I'm not sure "data science" fully captures that complexity. Even Action 14 describes a larger scope of staff data skills needed. 

Feedback Type (Question # of Other) 4
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment: Action 9 being due before Action 16 is particularly concerning, especially when it is specifically mentioned in the description of the action. Potentially more concerning, is the desire to share datasets with a large variety of stakeholders before Action 4, Develop a Data Protection Toolkit, is completed as well. 

Feedback Type (Question # of Other) 4
Author: Samantha Wu
Affiliation: Stae
Independent (Y/N): Y
Comment: I'm interested to know more regarding Action 10. Why is spending transparency only for IT? Is it because there are proven metrics for making "data-driven decisions" in IT but not in other areas of spending? Also, from my understanding, the world of grant reporting has not come to consensus on what actually proves impact. What grant metrics will be used based upon what expertise?

**Comment by ftrotter** [comment]
Samantha/Stae comments are reasonable and I agree in principle with all of the things she says here. 

The theme from Samantha's comments seems to be "what happens after", which is really a good meta comment on all of the action items. 

I further suggest that each action item have a new section of bullet list style "possible subsequent actions that should be supported by the completion of this action item" that should either explicate some second phase action items, or at least refer to overarching priorities that are the end-goals. 

Good items might be something like "to support later agency wide deployment of XYZ" etc etc.

**Comment by samwu8912** [comment]
@ftrotter on a related note, I recently reviewed the [Victorian Public Service's Data Reform Strategy](https://www.vic.gov.au/data-reform-strategy) and while it was obviously at a much later stage of the process than this one, I still think it was a pretty interesting example.

**Comment by ftrotter** [comment]
Good point. Crowdsourcing references like this might be a good use of this github platform. 

Its the kind of thing that might be useful to policy makers but hard to otherwise provide them. 

I had certainly never heard of that effort.

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
