### ISSUE TITLE
Response to Business Software Alliance comments

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#87]
Thank you for accepting GitHub-based comments for the next step of the Federal Data Strategy. This provides a unique mechanism to allow for commenters to respond to other commenter’s suggestions. In this case, I would like to respond to the comments submitted by the Business Software Alliance.

https://www.regulations.gov/document?D=USBC-2019-0001-0016

I should start out mentioning that I came into Open Data by way of Open Source Software, which should explain my slant on the BSA comments.

The first and only topic for which I completely disagree is the simple assertion at the beginning of their comments that "BSA is the leading advocate for the global software industry". This is decidedly false. BSA is the leading advocate for large proprietary and cloud-based software companies. The BSA regularly advocates for policies that front line developers completely disagree with. Advocating for the companies which hire developers is not the same thing as advocating for developers. More importantly, the vast majority of software that is developed in the world is done by small custom development shops or under Open Source licenses on GitHub, etc. The BSA regularly advocates against Open Source principles and community when those interfere with the financial interests of its members.

One would expect this distinction to matter tremendously in their recommendations. After all, the vast majority of data is held in Open Source databases from vendors who choose not to participate in the BSA for obvious reasons. Similarly, most data is hosted on operating systems developed by a community of people who mistrust the BSA.

Happily, despite this central disagreement I find myself agreeing with the vast majority of the advice given by the BSA in this case. For the most part, the things that they are suggesting are good for any commercial interests outside the Federal Government. Typically BSA tends to look out for the commercial interests of vendors who seek rent-seeking vendor lock (via license or cloud services) to valuable government contracts.

While I agree with much of what the BSA has to say, there is one place I disagree. The BSA argues for the unlocking of funds for IT modernization from the Modernizing Government Technology Act. They are frustrated that their vendors have not been adopted as much as they feel they ought to have been and they are seeking to use Federal Data Policy to unlock that treasure chest. I must disagree with this aim.

For data processing, data storage, and data analysis Open Source is the gold standard. Vendors who support Open Source data technologies have a difficult time getting approved for things like FedRAMP accreditation, because in the end they are giving away their underlying technology for free. Having to pay for the privilege of providing a free service is not a great business model.
The proprietary/cloud members of the BSA can afford to become certified and then recoup their costs by charging per-seat licenses or per-seat usage fees to the government.

But Open Source vendors simply charge for support for their products and typically encourage their clients to "scale for free" which is the central advantage of Open Source databases, etc. This is the reason for the success of Open Source in the database space and why, by data volume, the amount of data in Open Source databases far out-scales data in proprietary systems.

This matters for all IT systems, but for data this is especially true.

Instead of making more funds available for IT modernization related to data, the government should make less funds available and re-purpose funds to buying inexpensive support for Open Source databases across the Federal Government. Doing this will free up funds for data training, data maintenance and countless other tasks. The data strategy should proactively evaluate the top 2-3 Open Source database software projects for every type of database and then approve those software systems for Federal use. This would save billions of dollars over time that could be repurposed to helping the Federal Government solve problems that frequently require substantial resources. This includes the difficult healthcare data analysis problems that I am primarily concerned with.

Currently the Federal Government's database acquisition strategy is to have massive preference for bad deals. The rest of the software industry (despite BSA members insistence otherwise) has moved on to charging for higher level services and regards the database layer as a solved problem. The fact that there is a program to get into the "cloud" is just a mechanism for the Federal Government to access those modern cost realities without actually having to change the way it buys things. It is time for the Federal Government to radically rethink the way it approaches database software and to explicitly favor Open Source solutions.

When a database or other data software vendor is considered for a committee role, there should be an Open Source advocate along side. This should counterbalance the rent-seeking behaviors that are typical of the membership of BSA.

Again, on balance I find the comments from the BSA on other matters sensible and support them.

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
