### ISSUE TITLE
Leverage Open Source software across data assets in the Federal  Government

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#88]
This post in response to the action plan in the [Federal Data Strategy](https://strategy.data.gov/). 

As I mentioned in my [response to the BSA proposal](https://github.com/GSA/data-strategy/issues/87), the Federal Government should focus on leveraging Open Source software to process, host and analyze data.  

I have just read the [Cloudera Comments](https://www.regulations.gov/document?D=USBC-2019-0001-0017), and they have well articulated this notion, even better than I did in my BSA response. 

The Federal Government could save billions implementing Open Source databases, data pipeline tools and data analysis systems. Those billions should be applied to solving harder data problems, including wide-spread data literacy training for Federal employees. There are  plenty of companies, like [Cloudera](https://www.cloudera.com/), who are willing to make mere millions supporting Open Source solutions rather than billions that have spent on proprietary databases like Oracle and Microsoft. 

I am not sure this is something that can get much traction in the 24 hours before these comments are due, but I am pretty sure the whole Internet would agree on this one. 

-[Fred Trotter](https://fredtrotter.com)
CTO and Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
