### ISSUE TITLE
Responding to comments from Edward Kissam

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#89]
I am responding to [comments on the Federal Data Strategy Plan from Edward Kissam](https://www.regulations.gov/document?D=USBC-2019-0001-0002)

I do not know Edward, but I suspect I would like him. He complains articulately, and as someone who considers himself a professional complainer-to-the-government, I appreciate someone expressing concerns he obviously understands very well.

Having said that, I do not know enough about the underlying census data to know if most of his points are correct.

However, the overarching point he is making in his comments is something that I can get behind. There is no component of the current Action Plan that deals with the consistent wilful positions of specific Federal Government employees who contradict the overall strategy of openness and transparency that was well-articulated in both law and policy for more than a decade.

There needs to be a simple complaint system in place (not unlike this GitHub issue tracker) in which government employees are asked to respond to complaints like those leveled by Mr. Kissam and myself regarding a specific data project within the Federal Government which is going tremendously wrong.

Having the ability to comment on regulation is nice, but we need a way to provide feedback on the data projects in the Federal Government that are going side-ways, and have mechanisms for that feedback to be taken seriously and addressed in a transparent manner.

One previous attempt to do this was the Demand Driven Open Data project run by HHS which was also implemented with GitHub issues.

The community obviously embraced that effort and provided multiple high-quality suggestions, but once the government employee behind the project moved on, the contents of that "suggestion box" have gone cold.

The following suggestion should be implemented in Action 16: Identify Priority Datasets for Agency Open Data Plans. Which should be expanded to use some kind of "open data request issue tracker" like the Demand Driven Open Data project, and also have a measure of the responsiveness of the government.

The measures should be very simple:
1. The number of tickets closed by data requester because the answer given by a federal employee who addressed their need for open data
2. The sum of the distinct GitHub users who participated in the closed issue. 

These will provide an objective measure of the performance of the government in actually releasing the data "identified as priorities" by those outside the government, and is compatible with the principles of:
* Promote Transparency
* Ensure Relevance
* Demonstrate Responsiveness

There are several practices that would be supported by this action, I hope I can leave them to the reader's imagination.

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
