### ISSUE TITLE
Response to IBMs comments

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#90]
[Comments from IBM](https://www.regulations.gov/document?D=USBC-2019-0001-0005) endorse the [Community Data Licensing Agreements](https://cdla.io/) from the Linux Foundation.

While this seems progressive, data maintained in the Federal Government belongs in the public domain, with no licensing restrictions of any kind, including those put in place to "facilitate sharing". Licensing anything under any license requires that the Federal Government claim copyright to the data, and this is not the position that the government should take.

To claim copyright, even if it was for the purposes of then using an "open license" implies that the Government could also choose to license the data under non-open terms. This is an implicit power grab that puts the Federal Government in the position to have the public pay twice for the data, once in the form of taxes and again in the form of licensing concessions.

Instead, the government should seek to release all of its data directly into the public domain, as much as possible. Systems like PACER which have historically charged for access in a horribly inefficient manner, should be made to stop, and release its data repository into the public domain in raw formats. While the government would lose the income it got to maintain PACER, it does not actually need to maintain the front end to the system. Instead the Federal government should simply release the data. The same goes for NTIS.gov data and other similar data sales systems.

By collapsing these systems into raw-data download mechanisms, the expense to maintain these "storefront" systems would be removed and the government could get out of the "business" of selling access to data products. If done correctly, I believe that this would result in a net positive revenue result by reducing the cost of all data stores.

Action 16 should be modified to evaluate if for-pay datasets from the government make sense, given the new legislation. This improved action should measure if charging for data makes up for the costs of running multiple data stores across the Federal government. A new measure should be added to Action 16 to ensure that a cost estimate for hosting data stores was generated by the action. 

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by ftrotter** [comment]
Note, ensuring that data is available to download in the raw will help services like Internet Archive download data. Currently, any data that requires a login process (endemic to data stores like NTIS and PACER) cannot be automatically backed up in the Internet Archive. 

This is compatible with the advise found in the [PEGI comments](https://www.regulations.gov/document?D=USBC-2019-0001-0018) which note that almost no action items have focused on the issues of long term data preservation. Almost of all of PEGIs suggestions on this matter are worthwhile. 

-Fred Trotter
Healthcare Data Journalist.

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
