### ISSUE TITLE
Response to Microsoft Comments

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#91]
[Microsoft's comments](https://www.regulations.gov/document?D=USBC-2019-0001-0014) indicate that Microsoft believes that it has products and services that could help the government with Open Data efforts. And indeed they may. Some of the work they have done on privacy standards look very promising, for instance. 

However, the [Microsoft Open Data Initiative](https://www.microsoft.com/en-us/open-data-initiative) sounds like it might have something to do with data being open to the public (the normal definition of "Open Data") but in fact it has to do with Microsoft's ongoing efforts to be data "compatible" with other companies. While that is interesting and useful, it has little to do with the Open Data movement that is celebrated in the Federal Data Strategy.  The government should be aware that Microsoft is releasing exactly zero data to the public under that misnamed program. 

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
