### ISSUE TITLE
Response to comments from SIIA

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#92]
Ironically, SIIA is the second organization to claim, falsely, that the are the "principal trade association for the software and digital information industries worldwide." in [their comments](https://www.regulations.gov/document?D=USBC-2019-0001-0007). 

Again, most software developers are not members of SIIA and do not endorse the positions that they take. This is especially true of their comments here. 

SIIA is putting forward the standard arguments about the need to respect private "intellectual property" rights in data. And indeed this vague and unfortunate term is found throughout the Foundations for Evidence-Based Policymaking Act of 2018.

While the term "intellectual property" is used frequently by people who work with trademarks, patents and copyrights to talk about their work. And indeed, the term has slowly leaked into legal decisions and laws over the years. But strictly speaking this term is what [Richard Stallman calls a Seductive Mirage](https://www.gnu.org/philosophy/not-ipr.en.html).  To quote Stallman on the term from the article above:

_The term carries a bias that is not hard to see: it suggests thinking about copyright, patents and trademarks by analogy with property rights for physical objects.... These laws are in fact not much like physical property law, but use of this term leads legislators to change them to be more so. Since that is the change desired by the companies that exercise copyright, patent and trademark powers, the bias introduced by the term “intellectual property” suits them._ 

Referring to the results of any thought-work as though they are real-property is an act of intellectual dishonesty. I very much enjoy the apartment in Houston that I am sitting in as I write this message. And if I am using this apartment, it means that someone else cannot use it. With digital resources this is not true. It is not true for a website, or music, or youtube video or trademark or patent or anything else that is lumped in with the term "intellectual property". In fact, results of science or anything that could be considered "evidence" under the name of the law is worthless if it is "ownable". The value and legitimacy of evidence only increases beyond zero as it is shared among the community of thinkers who care about any given subject. 

On first glance, it may seem that the Foundations for Evidence-Based Policymaking Act of 2018 is supportive of the SIIA's position. But a careful read produces results in this central and typical passage:, under PART D--ACCESS TO DATA FOR EVIDENCE

_Nothing in this section may be construed as altering existing intellectual property rights or the  terms of any contract or other binding, written agreement._

But the key word  here is "existing". SIIA is seeming to imply that there is a lot of "existing" intellectual property or valid contracts. But data is just not the same as other forms of thought work. It is very difficult for data to be considered copyrightable, and it contracts that seek to limit the government use of simple facts cannot be binding. 

The notion that evidence cannot be openly shared, due to an expansive and broad definition of "intellectual property" is an opposed to the entire Federal Data Strategy, to the Open Data movement, and also to science and evidence gathering efforts more generally.

There is clear legal precedent that raw, unrefined data cannot be owned at all. Suppose there is a  McDonald's at the corner of Elgin and Cullen in Houston (spoiler, there is one there), and the location of that McDonald's property is at 29.727934, -95.344894 lat/lon. Then that is a fact about the world. I got that "data" from Google maps. But I could also drive out to that property and look at the street signs and the arches and look at the GPS on my phone. Because of this, decisions regarding the copyright-ability of data have been clear and consistent, one cannot copyright a fact about the world. Google cannot claim to "own" the fact that there is a McDonald's in that location. 

Even simple coding systems, like phone numbers, have been held to not meet the creativity threshold for copyright-ability. It is extremely dangerous to assert that "intellectual property" rights, which would presumably mean copyrights in this case, could ever apply to facts about the world.
 
Admittedly this makes it difficult for companies like Google to release facts that were gathered about the world at great expense. Google and others seek to ensure that the value of that work is protected. But the fact this represents a difficulty for them should not be made to construe that they own the underlying facts, which is what SIIA implies. SIIA puts forward two examples, traffic light data and weather data, which both have clearly no "creativity" involved. They are just facts, and the notion that a business can "own" those facts is just silly. 

Most companies use licensing agreements for data in order to get around this issue. The use contracts to ensure that valuable efforts are protected from being reduced in value by wanton data releases. Indeed the Federal Government has been willing to agree to such data licenses in the past. These contracts are not valid, and Open Data mandates must be honored over invalid and non-binding agreements which rely on the pretense that data is own-able. 

It is unacceptable for the Federal Government to put itself in the position of acquiring facts about the world from a vendor and then making a promise that it will not expose those facts about the world under FOIA and other transparency mechanics. The notion that the Federal Government could use a fact in its policy making process that is then inaccessible to the citizen who has been impacted by the decisions made based on that fact is a complete contradiction to not only the principles of FOIA and the Open Data Act, but to the rule of law itself. 

Action 16 or any other action that seeks to account for exploring what datasets are maintained by the various agencies, must also seek to account for "licenses data" in its databases. When "data" means copyrightable/patented thought-work that can be legitimately licensed to the government then this should be noted. When the data in question is simple facts, and the government has signed a license in any case, then this should also be noted. These contracts should be unwound as part of a data release process. 

Even if data is copyrightable, the government should simply pay the owner of the copyrights adequately to ensure that the data can be released. Even copyrights should not encumber open data access when policies and laws are enforced based on copyrighted data. When data is not simple, and can be subject to copyright, then the government should explicitly pay the copyright owners for the right to release the data broadly. While many private organizations might be frustrated by this posture, in many case the data in question has no intrinsic value beyond the fact that it is used and endorsed for use by the Federal Government. This is true of multiple coding sets leveraged by CMS, including CPT codes from the AMA and datasets provided by NCPDP. 

SIIS says "Therefore, any Federal Data Strategy should not nullify intellectual property or contractual rights of private sector partners." But in reality no such nullification can take place, because no such rights exist for simple data. 

All action items should account for the underlying principle that simple data is not copyrightable. Aggregations on those simple data by Federal data analysis should also remain in the public domain, even if they would be copyrightable if they were done by private citizens. 

This is what Open Data, transparency and evidence handling require. 

[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist at [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
