### ISSUE TITLE
ACT-IAC - AI Working Group response 

### ISSUE THREAD

**Issue by rajtiwari07** [GSA/data-strategy#97]
[ACT-IAC - AI Working Group response.docx](https://github.com/GSA/data-strategy/files/3370893/ACT-IAC.-.AI.Working.Group.response.docx)
If you haven't already reviewed the 2019-2020 Federal Data Strategy Action Plan, please first read http://strategy.data.gov/action-plan/

Please provide comments on the scope and content of the 2019-2020 Federal Data Strategy Action Plan.

1. Identify any additional fundamental actions to implement the Federal Data Strategy that are not included in this draft Year-1 Action Plan and explain why.
2. Identify any additional actions that would align with or complement ongoing Federal data initiatives or the implementation of new legislation, such as the Foundations for Evidence-based Policy Making Act and explain why.
3. Identify any actions in this draft Year-1 Action Plan that should be omitted and explain why.
4. For each action, provide any edits and additional detail to ensure that they accurately and effectively describe needed activities, responsible entities, metrics for assessing progress, and timelines for completion.
5. For each action, provide information about the implementation resources necessary to ensure success of these Action Steps.    

Please provide feedback using the guidance below to help us incorporate your feedback accurately:

* Specify the number of the question to which your comment applies.
* If possible, structure your comments on specific actions in the draft Year-1 Action Plan so that they refer to the number of the relevant action. If you have multiple comments on one action, please organize them together by action number.
* If possible, provide comments in a Microsoft Word or plain text file and avoid using footnotes, end notes, images, graphics, or tables. If you refer to reference material (documents, websites, research), please quote or paraphrase the specific content from referenced material.
* If you attach a PDF, please only post machine-readable PDFs.
 
Comments on issues not related to the Federal Data Strategy will not be considered.
 
Please submit comments by July 5, 2019.

When you create a new issue here on GitHub please fill out the template below. You can delete these instructions
==========================================
Feedback Type (Question # or Other): Comments
-----Contributors: 
Government : Sandy Barsky (GSA) - sandy.barsky@gsa.gov  
 ACT-IAC:  Raj Tiwari:  FORBES Technical Council, Co-Chair IEEE Future Direction                           
                 Digital Committee) raj.tiwari@ieee.org 
                  Mallesh , Murugesan (Co-Founder & CEO Abeyon ) 
                  Swathi Young - Chief Product Strategist  TechNotch Solutions

          Affiliation: Industry ( ACT-IAC AI Working Group)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
