### ISSUE TITLE
Response to comments from Socrata

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#98]
As enthusiastic as I am about Open Source generally  (and I hope I have demonstrated that enthusiasm in other comments) I must echo my support for Socrata's point that have an Open Source application, maintained by the Federal Government to exclusively run a data catalogue is probably a bad idea. It is also a bad idea to hire Socrata  *exclusively* to run the data catalogue. (Although Socrata does a very good job with the datasets that it releases, with responsive support and excellent documentation of its APIs, which work very reliably)

Instead, the Federal Government needs to focus more carefully on just making sure the underlying meta-data is actually "open in the raw". For this purposes, an FTP server would be entirely adequate. 

Data catalogues seem like a good idea, but they fail in several important ways: 

* First, they put dumb useless datasets right next to important datasets, without distinguishing between them in any useful way. 
* Second, they put a barrier between the data owner inside the government and any person who wants to reach that Federal employee about something dumb that they have done in the data release. Sadly, data release are frequently dumb in some way. 
* Second, there is no mechanism  for vetting and improving meta-data, even when the meta-data released is obviously wrong, limited or bone-headed. 

Instead, the Federal Government should focus on releasing the following in a machine-readable tree structured download repository: 

* One text file that links to the source of the raw data
* Another pdf file that details a "data specification" or "data datasheet" of the data in question
* One text file that links to the monitored ticket tracker for reporting bugs in the data,  data structure or data documentation. 

Then federal government should sponsor both Socrata and competent competitors and multiple open source systems to grok and refine these raw resources into something comprehensive. 

For our part, we have frequently considered leveraging Socrata's excellent capabilities in order to provide tools that do higher level ordering, but it is not easy to do what Socrata does well, and so those efforts really need to start with something as good for data releases as Socrata, and frankly, very few systems work as well as Socrata.  Socrata is not without its warts, and I have plenty of complaints about Socrata hosted data, but for the most part my beef is with the quality of the underlying data, and only very rarely do I have a problem that is actually due to Socrata as a company (they are called something else now, but they will always be Socrata to me)

[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist at [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
