### ISSUE TITLE
Edits to Action 1: Create an OMB Data Council.

### ISSUE THREAD

**Issue by ftrotter** [GSA/data-strategy#99]
Responding to: 
4. For each action, provide any edits and additional detail to ensure that they accurately and effectively describe needed activities, responsible entities, metrics for assessing progress, and timelines for completion.
5. For each action, provide information about the implementation resources necessary to ensure success of these Action Steps.    

for Action 1: 

It is not at all clear that the OMB Data Council is the same thing as the “Advisory Committee on 
Data for Evidence Building” required in the Open Data Act. If it is not the same thing, it should be merged together with this effort. A Federal employee-only “Data Council” would create competitive and contradictory goals as the “Advisory Committee on Data for Evidence Building”. Which specifically calls for data expertise outside of the Federal Government. 

The law is not accidental in its design that the OMB needed specific help with the following topics:

At least one shall have expertise in transparency, privacy policy, statistical data information management, information technology, as well as experience with research evaluation. In the sad event that there is going to be an OMB Data Council that is distinct from the “Advisory Committee on Data for Evidence Building” then the requirements for the OMB Data Council must be largely similar to the requirements for the first group. From now on, this advice will assume that only one council is being created, but in the event that two are created, then this advice is identical to both councils. 

First, there are twelve governmental appointees to the data council, there should be 12 non-governmental appointees, as well. The law says at least 10, but it is good form to have exactly the same number of Federal government employees and not Federal Employees. 

There are 6 requirements for members of the group who are “representatives of State and local governments and nongovernmental stakeholders”. No member of the council, inside or outside the government should not demonstrate at least some experience with at least four of these areas of expertise. As written these expertise listing are very general, and need to be narrowed down with very specific requirements. For instance, for the purposes of this committee, 

* An individual with “ expertise in transparency policy” must have participated (as government insiders or outsiders) in the release at least one dataset from the government for public use
* An individual with “expertise in privacy policy” must have demonstrated public writing (books, academic papers, manuals, blog posts, pamphlets, anything goes) about privacy practices
* An individual with “expertise in statistical data use” must have taken a statistics course
*  An individual with“expertise in information management” must have maintained a production database in the last 10 years 
* An individual with “expertise in information technology” must have written SQL in the last 15 years
* A member of the “research and evaluation community” must have work referenced in that academic arena  

We can imagine as similar, if looser list of qualifications of people who might merely have “experience” rather than “expertise”. The point here is to not be hand-wavy about requirements for this leadership community. No military council would form without a majority of participants having first-hand experience with warfare. People who understand what it means to be bloodied in battle, to shoot and be shot at. We need “in the trenches” experience for data leadership too. For data expertise there is simply no substitute for the experience of:

* losing critical data because the wrong type of JOIN was used in a SQL statement, 
* understanding when to use HAVING vs WHERE to apply a privacy threshold on a dataset, 
* having fought to counter selection bias in survey data. 
* the frustrations of having statistical significance without meaningful effect sizes,
* not having enough data points to make any conclusions at all. 
* experiences with CRUD software, 
* data transformation, 
* data validation and most importantly, 
* what happens when these things have all gone wrong. 

These are the type of experiences of what it means to “be on the front-line” of data use. The notion that you will get sensible policies from a group formed without these types of experiences is just silly. If you want to make policies about surgery, you need to involve surgeons. If you want to make policies about truck drivers, you need to involve truck drivers. But even more profoundly than those analogies, if you want to make policies about literacy, you need to have people who are literate, and writers. If you want to make policies about data, then you need people who create, manage and analyze data centrally involved.   

But not all that goes for “expertise” is useful. No expert should be able to join this council if their body of work is merely to criticise the privacy and open data actions taken by others. There are multiple people who claim to be experts in “privacy” but have only one real message “all data releases have privacy risks, so either release nothing or cripple the usefulness of data releases to protect privacy”. Open Data policies have casualties. Those who are hurt because of privacy breaches and mosaic attacks, and those who are hurt because our data policies have crippled real research into problems like forest fires, automobile accidents, and Alzhiemers disease. There is no harmless policy choice available. Your council should be formed by people who have practical experience striking the balance between these ends, and not those who spend their careers pointing out how others have failed as they worked to strike that balance.

There are dozens of people working in this space, both in and outside the government who have experience with all six of these criteria, and can claim expertise in more than two. Given that, why should we not require that members have at least four? And why not ensure that the members of this group have not only strategic experience, but real-world tactical experience as well? 

Beyond this, I recommend that the government seek out council members who have specific experience in privacy and open data that include: 

* Patient data 
* Employee data
* Student data
* Automobile data
* Geospatial data
* Social media data

Rather than merely evaluating candidates for this council they should be scored on their claims of expertise and experience, both in the areas specifically mentioned in the law as well as experience with the complex data areas listed above. 

-[Fred Trotter](https://fredtrotter.com)
CTO and Healthcare Data Journalist [CareSet Systems](https://careset.com)

**Comment by rebeccawilliams** [comment]
Thank you for providing feedback on the [draft Action Plan](https://github.com/GSA/data-strategy/tree/master/pages), the Federal Data Strategy team values your input! You can review the [final 2020 Action Plan](https://strategy.data.gov/action-plan/) and read more on [how the team revised the Action Plan based on feedback on Strategy.data.gov](https://strategy.data.gov/assets/docs/2019-2020-federal-data-strategy-revisions-based-on-feedback.pdf). You can also stay abreast of Federal Data Strategy updates by following [Strategy.data.gov/News](Strategy.data.gov/News).
